# Site settings
title: Rubbish Philosopher
email: suminb@gmail.com
description: "This statement is false."
baseurl: ""
url: "http://philosophical.one"
permalink: /posts/:title/
paginate: 15
paginate_path: /pages/:num
google_analytics_id: UA-346833-1
disqus: true
username: suminb

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
  - jekyll-paginate
