# Site settings
title: Rubbish Philosopher
email: suminb@gmail.com
description: "This statement is false."
baseurl: ""
url: "http://blog.suminb.com"
permalink: /post/:title
paginate: 15
paginate_path: /page/:num
google_analytics_id: UA-346833-1
disqus: true

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
